#
# This source file is part of the TemplatePackage open source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: OMHModels
      artifactname: OMHModels.xcresult
  packagewatchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: OMHModels
      resultBundle: OMHModelsWatchOS.xcresult
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)'
      artifactname: OMHModelsWatchOS.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      xcodeversion: latest
      scheme: OMHModels
      resultBundle: OMHModelsVisionOS.xcresult
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      artifactname: OMHModelsVisionOS.xcresult
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      xcodeversion: '14.3.1'
      scheme: OMHModels
    permissions:
      security-events: write
      actions: read
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagewatchos, packagevisionos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: OMHModels.xcresult OMHModelsWatchOS.xcresult OMHModelsVisionOS.xcresult
