#
# This source file is part of the TemplatePackage open source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test Swift Package
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: OMHModels
      artifactname: OMHModels.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: OMHModels.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}